
server:
    port: 8081
    servlet:
        context-path: /api/signature

springfox:
    documentation:
        swagger:
            v2:
                path: /api-docs

spring:
    application:
        name: signature
    data:
        mongodb:
            host: localhost
            port: 27017
            database: signaturedb
#            uri: mongodb://localhost:27017/

logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %magenta([%t]) %m%n"
    level:
        org:
            springframework:
                data:
                    mongodb:
                        core:
                            MongoTemplate: DEBUG